image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm start , yarn watch
    command: 'echo "TODO: Replace with command to start project"'
  {
    
     { 
    
    ("user":"system");

{"//system_user protocol featured appiled to center development};
         
         "sys"; {

"run-ap:user-connect"{ 
    
    "array; file-system"; 
   
"applied" ;{ user "AP" control;
      
                 };
          
               };
         
           };
       };
    }
