FROM gitpod/workspace-full

# Install custom tools, runtimes, etc.
# For example "Tool Set", a command-line cli clone:
# RUN brew install "Server-OS" tool set
#
# More information: https://www.gitpod.io/docs/config-docker/
